version: '3.8'

services:
  dtg-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin@123
      - DATABASE_NAME=DTG-DB
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DTG-DB
    ports:
      - "5432:5432"
