version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: admin@123  # รหัสผ่านสำหรับผู้ใช้ postgres
      POSTGRES_DB: DTG-DB           # ชื่อฐานข้อมูลที่ต้องการสร้าง
      POSTGRES_USER: postgres       # ชื่อผู้ใช้สำหรับการเชื่อมต่อกับฐานข้อมูล
    ports:
      - "5432:5432"  # Map port 5432 ไปยัง port บนเครื่อง host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # เก็บข้อมูลใน volume
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
